// ============================================
// RoboLab Benchmark Registry (GENERATED FILE)
// ============================================
// Generated by scripts/update-robolab.mjs. Do not edit by hand.
// Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json
// Upstream generated_at: 2026-08-12T23:33:43Z
// ============================================

import type { Benchmark, ModelEntry } from '../types';

// Models discovered on the RoboLab leaderboard that are not part of the
// hand-maintained registry in src/data/models.ts. Existing registry entries
// always take precedence over these.
export const ROBOLAB_MODELS: Record<string, ModelEntry> = {
  'cosmos3': {
    id: 'cosmos3',
    name: 'Cosmos3-Nano-Policy',
    organization: 'NVIDIA',
    dateAdded: '2026-08-12',
  },
  'cosmos3-edge': {
    id: 'cosmos3-edge',
    name: 'Cosmos3-Edge-Policy',
    organization: 'NVIDIA',
    dateAdded: '2026-08-12',
  },
  'dreamzero': {
    id: 'dreamzero',
    name: 'DreamZero',
    organization: 'NVIDIA',
    dateAdded: '2026-08-12',
  },
  'paligemma': {
    id: 'paligemma',
    name: 'paligemma-binning',
    organization: 'Physical Intelligence',
    dateAdded: '2026-08-12',
  },
  'phoenix': {
    id: 'phoenix',
    name: 'Phoenix',
    organization: 'Geodesic',
    isOpenSource: false,
    dateAdded: '2026-08-12',
  },
};

export const ROBO_LAB: Benchmark = {
  id: 'robolab',
  name: 'RoboLab-120',
  shortName: 'RoboLab',
  description: 'RoboLab-120: 120 language-conditioned manipulation tasks (10 episodes per task) evaluated in high-fidelity simulation on DROID (Franka). Scores are the official default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
  iconEmoji: '🔬',
  category: 'simulation',
  paper: {
    title: 'RoboLab: A High-Fidelity Simulation Benchmark for Analysis of Task Generalist Policies',
    authors: ['Xuning Yang', 'Rishit Dagli', 'Alex Zook', 'Hugo Hadfield', 'Ankit Goyal', 'Stan Birchfield', 'Fabio Ramos', 'Jonathan Tremblay'],
    venue: 'RSS',
    year: 2026,
    arxivId: '2604.09860',
  },
  websiteUrl: 'https://research.nvidia.com/labs/srl/projects/robolab/leaderboard.html',
  githubUrl: 'https://github.com/NVLabs/RoboLab',
  metrics: [
    { id: 'sr', name: 'Success Rate', description: 'Overall success rate, default instruction variant', higherIsBetter: true, format: 'percentage' },
    { id: 'score', name: 'Subtask Score', description: 'Subtask-progress score x100', higherIsBetter: true, format: 'percentage' },
    { id: 'simple', name: 'Simple SR', description: 'Success rate on simple tasks', higherIsBetter: true, format: 'percentage' },
    { id: 'moderate', name: 'Moderate SR', description: 'Success rate on moderate tasks', higherIsBetter: true, format: 'percentage' },
    { id: 'complex', name: 'Complex SR', description: 'Success rate on complex tasks', higherIsBetter: true, format: 'percentage' },
    { id: 'procedural', name: 'Procedural SR', description: 'Success rate on the procedural competency axis', higherIsBetter: true, format: 'percentage' },
    { id: 'relational', name: 'Relational SR', description: 'Success rate on the relational competency axis', higherIsBetter: true, format: 'percentage' },
    { id: 'visual', name: 'Visual SR', description: 'Success rate on the visual competency axis', higherIsBetter: true, format: 'percentage' },
    { id: 'ee_speed', name: 'EE Speed', description: 'End-effector speed in cm/s, excludes inference time', higherIsBetter: true, format: 'decimal' },
    { id: 'ee_sparc', name: 'EE SPARC', description: 'End-effector spectral arc length, closer to 0 is smoother', higherIsBetter: true, format: 'decimal' },
  ],
  lastUpdated: '2026-08-12',
  taskTypes: ['manipulation'],
  scores: [
    {
      modelId: 'cosmos3',
      score: 36.8,
      details: { score: 51.9, simple: 40.6, moderate: 35.4, complex: 25.3, procedural: 27.3, relational: 49.3, visual: 26.1, ee_speed: 7.13, ee_sparc: -5.99 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'phoenix',
      score: 34.4,
      details: { score: 45.9, simple: 42.8, moderate: 25.6, complex: 22.9, procedural: 21.8, relational: 25, visual: 33.6, ee_speed: 6.13, ee_sparc: -5.55 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'pi0.5',
      score: 28,
      details: { score: 43.4, simple: 29.7, moderate: 31.5, complex: 13.5, procedural: 21.8, relational: 33.8, visual: 23.8, ee_speed: 5.35, ee_sparc: -8.34 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'dreamzero',
      score: 25.7,
      details: { score: 39.8, simple: 26.1, moderate: 30, complex: 14.1, procedural: 26.4, relational: 33.3, visual: 17.5, ee_speed: 3.64, ee_sparc: -6.41 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'cosmos3-edge',
      score: 22.9,
      details: { simple: 25.6, moderate: 23.3, complex: 11.8, procedural: 15, relational: 26.7, visual: 16.8, ee_speed: 7.04, ee_sparc: -5.46 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'pi0fast',
      score: 15.5,
      details: { score: 26.9, simple: 20.2, moderate: 13.3, complex: 2.9, procedural: 6.4, relational: 23.3, visual: 8.8, ee_speed: 4.6, ee_sparc: -9.63 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'gr00tn1.6',
      score: 7.2,
      details: { score: 17.1, simple: 8.8, moderate: 7.9, complex: 0, procedural: 2.7, relational: 10, visual: 5, ee_speed: 4.3, ee_sparc: -6.87 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'pi0',
      score: 5,
      details: { score: 12.2, simple: 7.2, moderate: 3.6, complex: 0, procedural: 0.5, relational: 6.4, visual: 1.9, ee_speed: 4.18, ee_sparc: -9.49 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
    {
      modelId: 'paligemma',
      score: 3.4,
      details: { score: 9.9, simple: 3.4, moderate: 4.9, complex: 0, procedural: 0.5, relational: 5.7, visual: 2.7, ee_speed: 1.93, ee_sparc: -16.52 },
      notes: 'Official RoboLab-120 result for the default instruction variant. Source: https://research.nvidia.com/labs/srl/projects/robolab/static/data/leaderboard.json (upstream data generated at 2026-08-12T23:33:43Z).',
    },
  ],
};
